server:
  port: 8001
mybatis:
  type-aliases-package: com.ethan.springcloud.pojo
  mapper-locations: classpath:mybatis/mapper/*.xml
  config-location: classpath:mybatis/config/mybatis-config.xml
spring:
  #应用名称
  application:
    name: springcloud-provider-user-8001
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: czyczy1212
    url: jdbc:mysql://localhost:3306/test?characterEncoding=utf8&useUnicode=true&serverTimezone=Asia/Shanghai


