
server:
  port: 3344

spring:
  application:
    name: springcloud-config-server-3344
  cloud:
    config:
      server:
        git:
          # 连接远程配置仓库 https
          uri: https://github.com/ethanCun/springcloud-config.git





