server:
  port: 8002

mybatis:
  type-aliases-package: com.ethan.springcloud.pojo
  mapper-locations: classpath:mybatis/mapper/*.xml
  config-location: classpath:mybatis/config/mybatis-config.xml

spring:
  #应用名称
  application:
    # 多个服务提供者的名称一致是均衡负载的前提
    #应用名称大写 小写后也变成了大写，所以消费客户端的REST_URI_PREFIX也必须要大写
    name: SPRINGCLOUD-PROVIDER-USER
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: czyczy1212
    url: jdbc:mysql://localhost:3306/db02?characterEncoding=utf8&useUnicode=true&serverTimezone=Asia/Shanghai



# eureka配置
eureka:
  client:
    service-url:
      # 发布到单机版注册中心
      #defaultZone: http://localhost:7001/eureka/
      # 发布到集群版注册中心
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    # 改变应用status描述
    instance-id: user-provider-8002

# actuator监控配置信息 点击微服务的status信息会跳转到这个页面
info:
  app.name: com.ethan
  company.name: myyj

