server:
  port: 8080


#eureka
eureka:
  instance:
    hostname: springcloud-consume-user
  client:
    #消费者不用注册自己
    register-with-eureka: false
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/


# 开启服务熔断和服务降级
feign:
  hystrix:
    enabled: true